### ISSUE TITLE
how to startup this application?

### ISSUE THREAD

**Issue by dark4eg** [jackblatch/OneStopShop#1]
1. drizzle.config.json file does not exist
2. error proxy 
| import { createProxy } from "next/dist/build/webpack/loaders/next-flight-loader/module-proxy"
> const proxy = createProxy("F:\works\qvedo\temp\OneStopShop\components\ui\tabs.tsx")
|
| // Accessing the __esModule property and exporting $$typeof are required here.

**Comment by jackblatch** [comment]
Sorry, the drizzle config was listed in the gitignore file. It's now been removed and shows in repo on main.

**Comment by dark4eg** [comment]
Thank you!
I will try to help in the form of a PR (in the near future) to run the application in a docker container

**Comment by jackblatch** [comment]
Thanks, that would be great.
